version: '3.7'

services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ports:
        - 9200:9200
      networks:
        - "elk-net"    
    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:8.4.3
        restart: always
        environment:
          - ELASTICSEARCH_URL=https://localhost:9200
        ports:
          - "5601:5601"
        networks: 
          - "elk-net"
        depends_on:
          - elasticsearch
    apm-server:
        image: docker.elastic.co/apm/apm-server:8.4.3
        cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
        cap_drop: ["ALL"]
        ports:
          - 8200:8200
        command: >
          apm-server -e
            -E apm-server.rum.enabled=true
            -E setup.kibana.host=kibana:5601
            -E setup.template.settings.index.number_of_replicas=0
            -E apm-server.kibana.enabled=true
            -E apm-server.kibana.host=192.168.27.151:5601
            -E apm-server.kibana.username=elastic
            -E apm-server.kibana.password=ZsStlniruji+HEaYkLQF
            -E output.elasticsearch.hosts=["192.168.27.151:9200"]
            -E output.elasticsearch.username=elastic
            -E output.elasticsearch.password=ZsStlniruji+HEaYkLQF
            -E output.elasticsearch.protocol=https
            -E output.elasticsearch.ssl.verification_mode=none
        depends_on:          
          - elasticsearch
          - kibana
        networks:
          - "elk-net"
        healthcheck:
          interval: 10s
          retries: 12
          test: ["CMD", "curl", "--write-out", "'HTTP %{http_code}'", "--silent", "--output", "/dev/null", "http://apm-server:8200/healthcheck"]

networks:
      elk-net:
         driver: bridge